### ISSUE TITLE
Sell Error - requires element of type 'String' but has type 'Number'

### ISSUE THREAD

**Issue by DarthDK** [galodoido794/FutAUTO#1]
It is not possible to sell the purchased items automatically because everythuing it tries to sell an item, the app throws an element type exception.

The message is

ERROR: SELL2 EX: The requested operation requires an element of type 'String', but the target element has type 'Number'

**Comment by macgregore** [comment]
how to launch the software? I downloaded it but nothing happens

**Comment by galodoido794** [comment]
Bug Fixed ... In 1 hour I will upload the new version

**Comment by DarthDK** [comment]
Thank you for your great work

**Comment by galodoido794** [comment]
Bug Fixed v4: https://filebin.net/iwh577ydhjvb2etb

**Comment by galodoido794** [comment]
Bug Fixed: https://filebin.net/iwh577ydhjvb2etb

Em ter., 20 de out. de 2020 às 14:25, DarthDK <notifications@github.com>
escreveu:
