### ISSUE TITLE
run the bots

### ISSUE THREAD

**Issue by macgregore** [galodoido794/FutAUTO#2]
how to launch the software? I downloaded it but nothing happens

**Comment by galodoido794** [comment]
Download on your phone and install the APK ....

**Comment by macgregore** [comment]
I did download the file to my phone and apk, what to do now?

**Comment by Benassi10** [comment]
Unlock search player please

**Comment by macgregore** [comment]
at the top I succeeded. very good work .
Can't we buy players?

**Comment by chegerg** [comment]
How can we search Player ? Donation on Patreon ?

**Comment by macgregore** [comment]
I don't understand what to say

**Comment by chegerg** [comment]
We can't buy players ?

**Comment by macgregore** [comment]
apparently I don't think so, I asked him but I don't understand his answer

**Comment by galodoido794** [comment]
I changed the way of searching for players (compared to version 20). So I need to finish and I hope you do the likes challenge and subscribe to the channel.

[github.com/galodoido794/FutAUTO/blob/main/challenge.md](https://github.com/galodoido794/FutAUTO/blob/main/challenge.md)

**Comment by macgregore** [comment]
Yes of course we will be there to like, and thus make donations to you afterwards

**Comment by macgregore** [comment]
is good

**Comment by Benassi10** [comment]
Please add the option to sniping players

Il mer 21 ott 2020, 16:40 macgregore <notifications@github.com> ha scritto:
