### ISSUE TITLE
It doesn't work..

### ISSUE THREAD

**Issue by fhxdz** [galodoido794/FutAUTO#3]
I don't know why, but I think because isn't an apk version, it's a zip version.

**Comment by galodoido794** [comment]
The file extension is APK, I just installed it on my phone.

It must be in your WINDOWS that is set to open in a specific program (zip) ....

**Comment by galodoido794** [comment]
This tutorial is from the previous version, but it still works for this new version:

https://autobotfifax.blogspot.com/2019/10/run-futauto-with-emulator-android.html

**Comment by galodoido794** [comment]
When downloading rename the extension to .APK

**Comment by macgregore** [comment]
unfortunately I don't understand

**Comment by galodoido794** [comment]
Link Alternative: https://gofile.io/d/0AUpuA

**Comment by fhxdz** [comment]
Thank you, I just change it to .apk and it works.
