### ISSUE TITLE
Buying players

### ISSUE THREAD

**Issue by SaumyaVyas7** [galodoido794/FutAUTO#4]
Please make it available on your app. We really need it at this stage.

**Comment by macgregore** [comment]
he's working on it, and for him to release him we have a challenge for him. Only a few members are missing on his youtube

**Comment by Gleydson13** [comment]
Eu não estou conseguindo comprar jogadores o que devo fazer

**Comment by Gleydson13** [comment]
Como eu faço?

**Comment by galodoido794** [comment]
https://github.com/galodoido794/FutAUTO/blob/main/challenge.md
